name: zju-ncov-hitcarder-action
description: ZJU-nCov-HitCarder Action.
author: Long0x0

branding:
  icon: mail
  color: blue

inputs:
  strname:
    description: zju account username(student name).
    required: true
  username:
    description: zju account username(student id).
    required: true
  password:
    description: zju account password.
    required: true
  dingtalk_token:
    description: dingtalk_token.
    required: false
    default: ''
  serverchan_key:
    description: serverchan_key.
    required: false
    default: ''
  pushplus_token:
    description: pushplus_token.
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Working
      env:
        STRNAME: ${{ inputs.strname }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        DINGTALK_TOKEN: ${{ inputs.dingtalk_token }}
        SERVERCHAN_KEY: ${{ inputs.serverchan_key }}
        PUSHPLUS_TOKEN: ${{ inputs.pushplus_token }}
      run: |
        cd ${{ github.action_path }}
        pip install -r ./requirements.txt
        python3 ./hitcarder.py
      shell: bash
